---
language: go
go:
    - 1.3
    - 1.4
    - tip
install:
    - go get gopkg.in/mgo.v2
    - go get github.com/nickvanw/ircx
    - go get github.com/mrshankly/go-twitch/twitch

services:
    - mongodb
