---
language: go
go:
    - 1.3
    - 1.4
    - tip
install:
    - go get gopkg.in/mgo.v2
    - go get github.com/sorcix/irc
    - go get github.com/mrshankly/go-twitch/twitch
    - go get github.com/go-martini/martini
    - go get gopkg.in/redis.v3
    - go get github.com/robfig/cron

services:
    - mongodb
